### ISSUE TITLE
Bug: VI API Link isnt reachable (https://api.dev-fe-onboarding.virtual-identity.com)

### ISSUE THREAD

**Issue by dannystey** [virtualidentityag/dev-fe-onboarding#68]

**Comment by jurekbarth** [comment]
Mhmm yes we never made it work, oops. It should be a server that randomly returns errors in different ways in between correct responses. The response should be in some weird JSON so the onboarder needs to transform the data first before using it. Feel free to start implementing something as a node js server so we can deploy it as a lambda function or something similar. Otherwise i will add it to my todo list 👍

**Comment by SheepFromHeaven** [comment]
@dannystey @jurekbarth we should then at least update the text with a notice, that this is not working :)

**Comment by dannystey** [comment]
@SheepFromHeaven @jurekbarth  i would rather remove it and add it whenever the api is ready

**Comment by SheepFromHeaven** [comment]
resolved by #79
